# Generated by Django 5.0.6 on 2024-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bookings_options_bookings_gr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='main/static/img/restaurants/')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='noreply@example.com', max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='+xxx-xxx-xxx-xxx', max_length=16),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='images',
            field=models.ManyToManyField(related_name='images', to='main.image'),
        ),
        migrations.DeleteModel(
            name='Plates',
        ),
    ]
