# Generated by Django 5.0.6 on 2024-06-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_image_remove_restaurant_image_restaurant_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
    ]
