# Generated by Django 4.2.1 on 2024-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_restaurant_delivary_restaurant_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='map',
            field=models.ImageField(default=None, upload_to='main/static/img/restaurants/maps/'),
        ),
    ]
