# Generated by Django 4.2.1 on 2024-06-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_restaurant_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(choices=[('low', 'إقتصادي'), ('medium', 'متوسط'), ('high', 'مرتفع')], default='low', max_length=20),
        ),
    ]
