# Generated by Django 4.2.1 on 2024-06-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_restaurant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(choices=[('low', 'إقتصادي'), ('medium', 'متوسط'), ('high', 'مرتفع')], default='midium', max_length=20),
        ),
    ]
