# Generated by Django 4.2.1 on 2024-06-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_restaurant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.CharField(default='no date', max_length=64),
        ),
    ]
