# Generated by Django 4.2.1 on 2024-06-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bookings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='name',
            field=models.CharField(default='UNKNOWN', max_length=64),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.CharField(default='UNKNOWN', max_length=64),
        ),
    ]
