# Generated by Django 4.2.1 on 2024-06-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_restaurant_delivary_remove_restaurant_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('european', 'أوروبي'), ('asian', 'أسيوي'), ('arabic', 'عربي'), ('traditional algerian', 'جزائري تقليدي')], default='european', max_length=30),
        ),
    ]
