# Generated by Django 4.2.1 on 2024-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_restaurant_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('européenne', 'Continental'), ('asiatique', 'Asiatique'), ('arabe', 'Arabe'), ('Algérienne Traditionnelle', 'algérienne traditionnelle')], default='Continental', max_length=30),
        ),
    ]
